### ISSUE TITLE
a few bugs?

### ISSUE THREAD

**Issue by gnomefish** [FactionC2/Faction#12]
**Describe the bug**
help load -> doesn't work
load unexisting_module -> seems to crash the agent...
clicking the "delete" button on the agent screen only works after restarting faction. Nothing happens when you click the button

** Error Message **
Please copy and paste any error messages here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Running Ubuntu 18.04.2 - clean install with FactionC2 and nothing else. Using Chrome/Safari in macOS for the GUI.

**Additional context**

**Comment by jaredhaight** [comment]
Core *should* be catching invalid modules before they get to the agent. I need to double check this logic.

Thanks for the bug report! 👍

**Comment by jaredhaight** [comment]
These should both be fixed now, thanks again!
