### ISSUE TITLE
CLI doesn't validate --external-address value

### ISSUE THREAD

**Issue by jaredhaight** [FactionC2/Faction#13]
**Is your feature request related to a problem? Please describe.**
In the [Faction CLI](https://github.com/FactionC2/CLI), its really easy to mess up the format of the `--external-address` parameter. It needs to be a URL (http(s)://x.x.x.x) but its really easy to forget that and just specify an straight IP address. When this happens, the DIRECT transport can't function

**Describe the solution you'd like**
The CLI should check the value of `--external-address` and make sure that it begins with either http:// or https://. If it doesn't, it should throw an error and stop setup.

**Additional context**
We should add a check [before the config file is generated](https://github.com/FactionC2/CLI/blob/master/factioncli/commands/setup.py#L94) to see if external-address was specified and if it was, make sure that it begins with "http://" or "https://". While we could do a simple check just to make sure it starts with http, I think its better to check for the full protocol as we might be able to catch more errors before they screw everything up.

The check should leverage the `error_out` method from `factioncli.processing.cli.printing` to print the error message if the check fails.

**Comment by digital-shokunin** [comment]
Looks like the changes need to be made here?
https://github.com/digital-shokunin/CLI/blob/master/factioncli/commands/setup.py

I can probably do this.

**Comment by jaredhaight** [comment]
Yeah, I think that's the most sensible place to address this.

**Comment by digital-shokunin** [comment]
If I do a sys.exit(1) after throwing the error is that ideal? Or is it better to return 1; or something.

**Comment by jaredhaight** [comment]
The `error_out` function mentioned above actually handles all this. Just pass it an error message, by default it'll exit out with 1 which is fine.

**Comment by digital-shokunin** [comment]
Ah, well then. I think I'm done, just need to test it locally.

**Comment by jaredhaight** [comment]
Oh heck, I was just seeing your first name before, not the username! Thanks for the help man!

**Comment by digital-shokunin** [comment]
Pull request created.
https://github.com/FactionC2/CLI/pull/9

**Comment by jaredhaight** [comment]
Merged. Thanks again for the PR!
