### ISSUE TITLE
Faction CLI should prompt for IP address if --external-address isn't specified

### ISSUE THREAD

**Issue by jaredhaight** [FactionC2/Faction#16]
**Is your feature request related to a problem? Please describe.**
Its really easy to miss the fact that `faction setup` by default will use the public IP address of the server if you don't specify one

**Describe the solution you'd like**
Faction should prompt the user with the IP its going to use

ex: `Please specify the IP address Faction should be reachable at. Press enter to use the detected IP of : x.x.x.x`

There should be an extra parameter for "don't prompt" or something

**Additional context**
Ultimately this is just used for the DIRECT transport, eventually we should have the ability to edit transport configs from the client, but thats going to be a pretty involved update. For now adding the prompt should be fine.

**Comment by c24dotspace** [comment]
Addressed by: [#11](https://github.com/FactionC2/CLI/pull/11)

**Comment by jaredhaight** [comment]
Great job! Thanks so much for the PR!
