### ISSUE TITLE
load winlib without response

### ISSUE THREAD

**Issue by Tru5tNo1** [FactionC2/Faction#20]
Describe the bug
load winlib 
-> (without response)
load stdlib 
-> (loaded)

transportserver  HTTP
Running Ubuntu 18.04

Additional Information:
Running Ubuntu 18.04.2 - clean install with FactionC2 and nothing else. 

Running Marauder on:
Windows 10 v.1803 build SO 17134.765

Using Firefox on Ubuntu

**Comment by s3b4stian** [comment]
Problem is not present with Direct Transport.

Http transport put payloads on http message headers. WinLib size exceeds the http header limit size.

For solve this need to put payloads to http request body.

**Comment by jaredhaight** [comment]
We re-wrote the HTTP Transport a month ago which resolves this issue. Thanks for letting us know!
