### ISSUE TITLE
.NET 4.5 Payload Generation Not Working

### ISSUE THREAD

**Issue by bashexplode** [FactionC2/Faction#33]
When using the admin interface of Faction to generate payloads, the .NET 4.5 option still generates payloads as .NET 3.5. I initially discovered this by executing the payload on a Windows Server 2012 R2 instance that did not have .NET 3.5 installed and was prompted with the 3.5 installation page for the framework.

I currently have the Faction server set up on Ubuntu 18.04.

**Comment by jaredhaight** [comment]
This was fixed with a push yesterday. Thanks for submitting an issue!
