### ISSUE TITLE
Failed to upload files

### ISSUE THREAD

**Issue by sckalath** [FactionC2/Faction#41]
Hey gang,

I'm having trouble uploading files through the UI. I've been able to generate payloads and agents without an issue. It just seems that I can't upload a file. Clicking the "Upload Files" button opens the file selection dialog but once the file is selected, nothing happens. 

I get a 500 error message, but no helpful details that I can find. No stack traces or anything that would tell me what's going on. 

![500](https://user-images.githubusercontent.com/4554027/75168915-81e0ab00-56dc-11ea-8301-b6395c278ed9.PNG)

Thanks!
Ryan

**Comment by 0x00xx** [comment]
can confirm, same error for me. Any fix would be appreciated

**Comment by jaredhaight** [comment]
Hey everyone! Thanks a lot for the bug report! 🙏 

I am totally focused on rebuilding Faction right now, so I won’t be able to spend time on this issue. The entire API is changing, which includes a new File service that should be more robust and will most likely fix this problem. 

I’ve been posting some articles detailing the progress of the rebuild here if you want more details: https://www.factionc2.com/articles/rebuilding-a-faction-part-1
