### ISSUE TITLE
API: Cannot POST content to /api/v1/agent/1/console/

### ISSUE THREAD

**Issue by highmeh** [FactionC2/Faction#8]
**Describe the bug**
The HTTP Request "POST" is not allowed by the API endpoint /api/v1/agent/1/console/

** Error Message **
> {'message': 'The method is not allowed for the requested URL.'}

**To Reproduce**
1. Authenticate to the Faction Server using the API
2. Send a POST request to "http://url:5000/api/v1/agent/1/console/?token=api:secret" with the data value of '{"Content:":"Test"}'
3. The error above is displayed and the content does not post to the console.

**Expected behavior**
Per the documentation at https://www.factionc2.com/docs/api/#post-agent-agent-id-console, the POST command should be allowed to send a message to the console. However, the following output from Wireshark shows that the POST request is not supported:

> HTTP/1.1 405 METHOD NOT ALLOWED
> Server: gunicorn/19.7.1
> Date: Fri, 12 Apr 2019 20:23:10 GMT
> Connection: keep-alive
> Content-Type: application/json
> Content-Length: 70
> **Allow: HEAD, OPTIONS, GET**
>
> {
>     "message": "The method is not allowed for the requested URL."
> }
> 

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jaredhaight** [comment]
Thanks for the issue @highmeh! This has been [fixed](https://github.com/FactionC2/API/pull/2)!
