### ISSUE TITLE
Marauder agent does not build on Ubuntu 18.04.2 LTS Virtual Machine

### ISSUE THREAD

**Issue by Tru5tNo1** [FactionC2/Faction#9]
Describe the bug
The default installation of FactionC2 does not allow you to build a Marauder payload with the DIRECT Transport.

Error Message

Timestamp: 2019-05-09T10:29:41.450521
Source: .NET Build Server
Message: Error building Marauder
Details:
Tried to build an agent without a Base64 encoded transport string. Transport build must have failed.
    

Launch a  Ubuntu 18.04.2 LTS Virtual Machine instance. 
VmWare 15

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

Execute:
curl https://raw.githubusercontent.com/FactionC2/Faction/master/install.sh | sudo bash
Execute:
sudo faction setup

Authenticate to FactionC2 console.
Navigate to the Payloads tab.
Select New Payload.
Set agent type to Marauder.
Set Architecture x64 (or x86, same results) 
Set transport type to Direct Transport. 
Set format to .NET 3.5(or 4.5, same results) 
Executable No Debug (or with debug, same results)
Click Create Payload.
Receive error above.

lsb_release -a:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

**Comment by jaredhaight** [comment]
Thank you so much for the bug report @Tru5tNo1! Pushed some changes and this should be resolved now. You can perform a clean install by running the following commands:

```
faction clean --all
faction setup <with whatever options you need>
```
